package com.yihukurama.www.mvpbuilder.framework.m.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String Oid;
    private String Name;
    private String Sex;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String Oid, String Name, String Sex) {
        this.id = id;
        this.Oid = Oid;
        this.Name = Name;
        this.Sex = Sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOid() {
        return Oid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOid(String Oid) {
        this.Oid = Oid;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

}
