package com.yihukurama.www.mvpbuilder.framework.m.dao.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private Long id;

    @NotNull
    private String Oid;
    private String Name;
    private String Sex;

    @Generated(hash = 586692638)
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated(hash = 231877795)
    public User(Long id, @NotNull String Oid, String Name, String Sex) {
        this.id = id;
        this.Oid = Oid;
        this.Name = Name;
        this.Sex = Sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getOid() {
        return Oid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOid(@NotNull String Oid) {
        this.Oid = Oid;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

}
